export interface FrameTemplate {
  id: string;
  name: string;
  description: string;
  emoji: string;
  containerStyle: React.CSSProperties;
  titleStyle: React.CSSProperties;
  subtitleStyle: React.CSSProperties;
  ctaStyle: React.CSSProperties;
  defaultTitle: string;
  defaultSubtitle: string;
  defaultCta: string;
  defaultPrimaryColor: string;
  defaultTextColor: string;
  qrWrapperStyle?: React.CSSProperties;
}

import type React from 'react';

export const FRAME_TEMPLATES: FrameTemplate[] = [
  {
    id: 'business-card',
    name: 'Business Card',
    description: 'Clean professional look',
    emoji: '💼',
    containerStyle: {
      background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
      borderRadius: '16px',
      padding: '24px',
      boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
      border: '1px solid rgba(255,255,255,0.1)',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '12px',
    },
    titleStyle: {
      color: '#ffffff',
      fontSize: '20px',
      fontWeight: '700',
      letterSpacing: '0.05em',
      textAlign: 'center',
    },
    subtitleStyle: {
      color: 'rgba(255,255,255,0.6)',
      fontSize: '13px',
      textAlign: 'center',
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
    },
    ctaStyle: {
      color: '#4361ee',
      fontSize: '12px',
      textAlign: 'center',
      fontWeight: '600',
      letterSpacing: '0.05em',
    },
    defaultTitle: 'John Doe',
    defaultSubtitle: 'Software Engineer',
    defaultCta: 'Scan to connect',
    defaultPrimaryColor: '#4361ee',
    defaultTextColor: '#ffffff',
  },
  {
    id: 'restaurant-menu',
    name: 'Restaurant Menu',
    description: 'Warm dining atmosphere',
    emoji: '🍽️',
    containerStyle: {
      background: 'linear-gradient(135deg, #8B4513 0%, #D2691E 100%)',
      borderRadius: '20px',
      padding: '28px 24px',
      boxShadow: '0 20px 60px rgba(139,69,19,0.4)',
      border: '3px solid #CD853F',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '14px',
    },
    titleStyle: {
      color: '#FFF8DC',
      fontSize: '22px',
      fontWeight: '800',
      fontFamily: 'Georgia, serif',
      textAlign: 'center',
      textShadow: '0 2px 4px rgba(0,0,0,0.3)',
    },
    subtitleStyle: {
      color: '#FFE4B5',
      fontSize: '13px',
      textAlign: 'center',
      fontFamily: 'Georgia, serif',
      fontStyle: 'italic',
    },
    ctaStyle: {
      background: '#FFD700',
      color: '#8B4513',
      fontSize: '13px',
      fontWeight: '700',
      padding: '6px 16px',
      borderRadius: '20px',
      textAlign: 'center',
    },
    defaultTitle: 'Our Menu',
    defaultSubtitle: 'Scan to view our full menu',
    defaultCta: '🍴 Order Now',
    defaultPrimaryColor: '#D2691E',
    defaultTextColor: '#FFF8DC',
  },
  {
    id: 'social-media',
    name: 'Social Media',
    description: 'Vibrant social style',
    emoji: '📱',
    containerStyle: {
      background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 50%, #4facfe 100%)',
      borderRadius: '24px',
      padding: '24px',
      boxShadow: '0 20px 60px rgba(240,147,251,0.4)',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '12px',
    },
    titleStyle: {
      color: '#ffffff',
      fontSize: '20px',
      fontWeight: '800',
      textAlign: 'center',
      textShadow: '0 2px 8px rgba(0,0,0,0.2)',
    },
    subtitleStyle: {
      color: 'rgba(255,255,255,0.9)',
      fontSize: '13px',
      textAlign: 'center',
    },
    ctaStyle: {
      background: 'rgba(255,255,255,0.25)',
      color: '#ffffff',
      fontSize: '13px',
      fontWeight: '700',
      padding: '6px 18px',
      borderRadius: '20px',
      textAlign: 'center',
      backdropFilter: 'blur(10px)',
    },
    defaultTitle: '@username',
    defaultSubtitle: 'Follow me for updates',
    defaultCta: '✨ Follow Now',
    defaultPrimaryColor: '#f093fb',
    defaultTextColor: '#ffffff',
  },
  {
    id: 'event-ticket',
    name: 'Event Ticket',
    description: 'Classic ticket stub style',
    emoji: '🎫',
    containerStyle: {
      background: '#1a0533',
      borderRadius: '16px',
      padding: '20px 24px',
      boxShadow: '0 20px 60px rgba(0,0,0,0.5)',
      border: '2px dashed rgba(255,215,0,0.5)',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '10px',
      position: 'relative',
      overflow: 'hidden',
    },
    titleStyle: {
      color: '#FFD700',
      fontSize: '21px',
      fontWeight: '900',
      textAlign: 'center',
      letterSpacing: '0.1em',
      textTransform: 'uppercase',
      textShadow: '0 0 20px rgba(255,215,0,0.5)',
    },
    subtitleStyle: {
      color: 'rgba(255,255,255,0.7)',
      fontSize: '13px',
      textAlign: 'center',
      letterSpacing: '0.05em',
    },
    ctaStyle: {
      background: '#FFD700',
      color: '#1a0533',
      fontSize: '13px',
      fontWeight: '800',
      padding: '6px 20px',
      borderRadius: '4px',
      textAlign: 'center',
      letterSpacing: '0.05em',
    },
    defaultTitle: 'EVENT 2025',
    defaultSubtitle: 'VIP Access Pass',
    defaultCta: '🎟 SCAN TO ENTER',
    defaultPrimaryColor: '#FFD700',
    defaultTextColor: '#FFD700',
  },
  {
    id: 'whatsapp-connect',
    name: 'WhatsApp Connect',
    description: 'Quick WhatsApp link',
    emoji: '💬',
    containerStyle: {
      background: 'linear-gradient(135deg, #128C7E 0%, #25D366 100%)',
      borderRadius: '20px',
      padding: '24px',
      boxShadow: '0 20px 60px rgba(37,211,102,0.35)',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '12px',
    },
    titleStyle: {
      color: '#ffffff',
      fontSize: '21px',
      fontWeight: '800',
      textAlign: 'center',
      textShadow: '0 2px 6px rgba(0,0,0,0.2)',
    },
    subtitleStyle: {
      color: 'rgba(255,255,255,0.85)',
      fontSize: '13px',
      textAlign: 'center',
    },
    ctaStyle: {
      background: '#ffffff',
      color: '#128C7E',
      fontSize: '13px',
      fontWeight: '800',
      padding: '8px 20px',
      borderRadius: '24px',
      textAlign: 'center',
    },
    defaultTitle: 'Chat with us',
    defaultSubtitle: 'Available 24/7',
    defaultCta: '💬 Message Now',
    defaultPrimaryColor: '#25D366',
    defaultTextColor: '#ffffff',
  },
  {
    id: 'website-cta',
    name: 'Website CTA',
    description: 'Drive web traffic',
    emoji: '🌐',
    containerStyle: {
      background: 'linear-gradient(135deg, #4361ee 0%, #7209b7 100%)',
      borderRadius: '20px',
      padding: '28px 24px',
      boxShadow: '0 20px 60px rgba(67,97,238,0.4)',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '12px',
    },
    titleStyle: {
      color: '#ffffff',
      fontSize: '20px',
      fontWeight: '800',
      textAlign: 'center',
    },
    subtitleStyle: {
      color: 'rgba(255,255,255,0.8)',
      fontSize: '13px',
      textAlign: 'center',
    },
    ctaStyle: {
      background: '#ffffff',
      color: '#4361ee',
      fontSize: '13px',
      fontWeight: '700',
      padding: '8px 20px',
      borderRadius: '8px',
      textAlign: 'center',
    },
    defaultTitle: 'Visit Our Website',
    defaultSubtitle: 'Discover more at our site',
    defaultCta: '🌐 Visit Now',
    defaultPrimaryColor: '#4361ee',
    defaultTextColor: '#ffffff',
  },
  {
    id: 'minimal-modern',
    name: 'Minimal Modern',
    description: 'Clean, minimal style',
    emoji: '⬜',
    containerStyle: {
      background: '#ffffff',
      borderRadius: '12px',
      padding: '24px',
      boxShadow: '0 4px 30px rgba(0,0,0,0.08)',
      border: '1px solid #e5e7eb',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '10px',
    },
    titleStyle: {
      color: '#111827',
      fontSize: '18px',
      fontWeight: '700',
      textAlign: 'center',
      letterSpacing: '-0.02em',
    },
    subtitleStyle: {
      color: '#6b7280',
      fontSize: '13px',
      textAlign: 'center',
    },
    ctaStyle: {
      color: '#4361ee',
      fontSize: '13px',
      fontWeight: '600',
      textAlign: 'center',
      borderBottom: '1px solid #4361ee',
      paddingBottom: '2px',
    },
    defaultTitle: 'Scan Me',
    defaultSubtitle: 'Quick access link',
    defaultCta: 'Tap to open →',
    defaultPrimaryColor: '#111827',
    defaultTextColor: '#111827',
  },
  {
    id: 'luxury-gold',
    name: 'Luxury Gold',
    description: 'Premium gold aesthetic',
    emoji: '✨',
    containerStyle: {
      background: 'linear-gradient(135deg, #1c1c1c 0%, #2d2d2d 100%)',
      borderRadius: '20px',
      padding: '28px 24px',
      boxShadow: '0 20px 60px rgba(0,0,0,0.6), inset 0 0 0 1px rgba(212,175,55,0.3)',
      border: '1px solid rgba(212,175,55,0.4)',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '14px',
    },
    titleStyle: {
      color: '#D4AF37',
      fontSize: '22px',
      fontWeight: '700',
      textAlign: 'center',
      letterSpacing: '0.08em',
      textShadow: '0 0 20px rgba(212,175,55,0.4)',
      fontFamily: 'Georgia, serif',
    },
    subtitleStyle: {
      color: 'rgba(212,175,55,0.7)',
      fontSize: '13px',
      textAlign: 'center',
      letterSpacing: '0.12em',
      textTransform: 'uppercase',
      fontFamily: 'Georgia, serif',
      fontStyle: 'italic',
    },
    ctaStyle: {
      background: 'linear-gradient(135deg, #D4AF37, #F5D060)',
      color: '#1c1c1c',
      fontSize: '13px',
      fontWeight: '700',
      padding: '8px 22px',
      borderRadius: '4px',
      textAlign: 'center',
      letterSpacing: '0.05em',
    },
    defaultTitle: 'Exclusive Access',
    defaultSubtitle: 'Premium Member',
    defaultCta: '✦ Scan to Enter ✦',
    defaultPrimaryColor: '#D4AF37',
    defaultTextColor: '#D4AF37',
  },
];
